dist: trusty
sudo: required

language: erlang
otp_release:
  - 22.0
  - 21.0
  - 20.0
  - 19.0
  - 18.0

script:
  - escript rebar3 eunit
  - escript rebar3 ct

addons:

before_install:
  - sudo docker-compose up -d
  - ./_download_rebar3.sh
